/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tickets
         * @description The inbox, highest priority first, then the most recently updated.
         */
        get: operations["list_tickets_api_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Internal Event
         * @description Publish an MCP server's event: handlers run and every /ws/staff connection gets it.
         */
        post: operations["internal_event_internal_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Inject a fake inbound message on any channel (a backup when a platform is down on stage).
         */
        post: operations["simulate_api_dev_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Channels
         * @description Which channel adapters are connected in this process, and where the others' replies go.
         */
        get: operations["channels_api_dev_channels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Chat Session
         * @description The pre-chat form: name and email → a new chat session. Public (customers have no account).
         */
        post: operations["create_chat_session_api_chat_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatSessionIn */
        ChatSessionIn: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ChatSessionOut */
        ChatSessionOut: {
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
        };
        /**
         * DevChannels
         * @description Which channel adapters this process runs (§15 checklist).
         */
        DevChannels: {
            /** Connected */
            connected: ("discord" | "telegram" | "email" | "web")[];
            /** Enabled */
            enabled: ("discord" | "telegram" | "email" | "web")[];
            /** Simulated */
            simulated: ("discord" | "telegram" | "email" | "web")[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "unreachable";
        };
        /**
         * InternalEventIn
         * @description What an MCP server POSTs to /internal/events.
         */
        InternalEventIn: {
            /**
             * Type
             * @enum {string}
             */
            type: "message.received" | "message.sent" | "ticket.created" | "ticket.updated" | "ticket.followup" | "agent.tool_called" | "payment.link_sent" | "payment.utr_submitted" | "payment.paid" | "payment.failed" | "job.assigned" | "job.status_changed" | "job.completed" | "job.rejected" | "stock.low" | "notification.created";
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RowCustomer */
        RowCustomer: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
        };
        /** RowDevice */
        RowDevice: {
            /** Model Name */
            model_name: string;
            /** Serial Number */
            serial_number: string;
            /** Color */
            color: string | null;
            /** Category */
            category: string;
        };
        /**
         * SimulateIn
         * @description A fake inbound message, handled as if the channel's adapter had received it.
         */
        SimulateIn: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "discord" | "telegram" | "email" | "web";
            /** Text */
            text: string;
            /**
             * External User Id
             * @description The sender's account on the channel (Telegram or Discord user id, email address, web session id). Leave it out for a new simulated customer; send back the one a response gave to go on with that conversation. A real chat id reaches that chat when its adapter runs here.
             */
            external_user_id?: string | null;
            /**
             * External Thread Id
             * @description The conversation's thread; external_user_id when left out.
             */
            external_thread_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Email
             * @description web: the pre-chat form's email, which links the customer. email: the sender's address when external_user_id is left out.
             */
            email?: string | null;
            /**
             * Subject
             * @description email only
             */
            subject?: string | null;
        };
        /** SimulateOut */
        SimulateOut: {
            /**
             * Channel
             * @enum {string}
             */
            channel: "discord" | "telegram" | "email" | "web";
            /** External User Id */
            external_user_id: string;
            /** External Thread Id */
            external_thread_id: string;
            /**
             * Delivery
             * @enum {string}
             */
            delivery: "adapter" | "simulated" | "none";
            /**
             * Customer Id
             * Format: uuid
             */
            customer_id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Awaiting */
            awaiting: string | null;
            ticket: components["schemas"]["SimulatedTicket"] | null;
            /** Replies */
            replies: components["schemas"]["SimulatedReply"][];
            /** Intake Error */
            intake_error: string | null;
        };
        /**
         * SimulatedReply
         * @description A reply intake queued for the simulated message.
         */
        SimulatedReply: {
            /**
             * Message Id
             * Format: uuid
             */
            message_id: string;
            /** Text */
            text: string;
            /** Status */
            status: ("pending" | "sent" | "failed") | null;
            /** Simulated */
            simulated: boolean;
            /** Last Error */
            last_error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SimulatedTicket */
        SimulatedTicket: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticket Number */
            ticket_number: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "in_progress" | "awaiting_customer" | "awaiting_payment" | "scheduled" | "resolved" | "closed";
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /** Flags */
            flags: string[];
        };
        /**
         * StaffEvent
         * @description One event, as /ws/staff sends it: {type, data, ts}.
         */
        StaffEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "message.received" | "message.sent" | "ticket.created" | "ticket.updated" | "ticket.followup" | "agent.tool_called" | "payment.link_sent" | "payment.utr_submitted" | "payment.paid" | "payment.failed" | "job.assigned" | "job.status_changed" | "job.completed" | "job.rejected" | "stock.low" | "notification.created";
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * StaffOut
         * @description A signed-in staff member, as /api/me and the login response return them.
         */
        StaffOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "agent" | "technician" | "warehouse" | "admin";
            /** City */
            city: string | null;
            /** Skills */
            skills: string[];
            /** Is Available */
            is_available: boolean;
            /** Avatar Url */
            avatar_url: string | null;
        };
        /** TicketList */
        TicketList: {
            /** Tickets */
            tickets: components["schemas"]["TicketRow"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * TicketRow
         * @description One inbox row (§11.3).
         */
        TicketRow: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticket Number */
            ticket_number: string;
            /** Title */
            title: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "in_progress" | "awaiting_customer" | "awaiting_payment" | "scheduled" | "resolved" | "closed";
            /**
             * Priority
             * @enum {string}
             */
            priority: "low" | "medium" | "high" | "urgent";
            /**
             * Category
             * @enum {string}
             */
            category: "hardware" | "software" | "unknown";
            /** Issue Type */
            issue_type: string;
            /**
             * Source Channel
             * @enum {string}
             */
            source_channel: "discord" | "telegram" | "email" | "web";
            /** Channels */
            channels: ("discord" | "telegram" | "email" | "web")[];
            customer: components["schemas"]["RowCustomer"];
            device: components["schemas"]["RowDevice"] | null;
            /** Ai Summary */
            ai_summary: string | null;
            /** Duplicate Count */
            duplicate_count: number;
            /** Flags */
            flags: string[];
            /** Assigned Agent Id */
            assigned_agent_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            staff: components["schemas"]["StaffOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description The database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Wrong email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description JWT_SECRET is not set */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Sign in again. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tickets_api_tickets_get: {
        parameters: {
            query?: {
                /** @description A status, or open: not resolved or closed */
                status?: ("new" | "in_progress" | "awaiting_customer" | "awaiting_payment" | "scheduled" | "resolved" | "closed") | "open" | null;
                priority?: ("low" | "medium" | "high" | "urgent") | null;
                /** @description Tickets whose conversation crossed this channel */
                channel?: ("discord" | "telegram" | "email" | "web") | null;
                category?: ("hardware" | "software" | "unknown") | null;
                assignee?: string | ("me" | "unassigned") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_event_internal_events_post: {
        parameters: {
            query?: never;
            header?: {
                "x-internal-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffEvent"];
                };
            };
            /** @description Wrong or missing X-Internal-Key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description INTERNAL_API_KEY is not set */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    simulate_api_dev_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not in development */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    channels_api_dev_channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevChannels"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not in development */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_chat_session_api_chat_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSessionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
